[all]
ctl1 ansible_host=192.168.0.181 ansible_python_interpreter=/Users/joeycoakley/Desktop/Git/controller_upgrade/env/bin/python
ctl2 ansible_host=192.168.0.182 ansible_python_interpreter=/Users/joeycoakley/Desktop/Git/controller_upgrade/env/bin/python
ctl5 ansible_host=192.168.0.185 ansible_python_interpreter=/Users/joeycoakley/Desktop/Git/controller_upgrade/env/bin/python