---
- hosts: all
  gather_facts: no
  connection: local
  vars_files: vars.yml
  any_errors_fatal: true
  collections:
    - vmware.alb

  tasks:
  # Check whether this is a GSLB-enabled Cluster
    - name: Check GSLB Enabled
      vmware.alb.avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        http_method: get
        timeout: 3000
        path: gslb
      register: gslb

    - name: Fail if GSLB NOT Enabled
      fail:
        msg: "This cluster has GSLB disabled. Please use non-gslb upgrade."
      when: gslb.obj.count == 0

    - name: Pull version file out of upgrade package
      unarchive:
        src: "{{ upgrade_file_location }}"
        dest: ./
        extra_opts:
        - --strip=1
        - --wildcards
        - 'bootstrap/VERSION'
      register: unzip_results
      run_once: True
      tags: 
        - prepare

  # get image version from upgrade file
    - set_fact:
        zip_image_version: "{{ lookup('csvfile', 'Tag file=./VERSION delimiter=:') | trim}}"
      tags:
        - prepare

  # Search image list for our current upgrade
    - name: get image list
      vmware.alb.avi_api_session:
        avi_credentials: "{{ avi_credentials }}"       
        http_method: get
        timeout: 3000
        path: image
      register: image_list
      tags:
        - prepare
      
    - set_fact:
        image_name: "{{image_list.obj.results | json_query(name_query) }}"
        image_type: "{{image_list.obj.results | json_query(type_query) }}"
        image_uuid: "{{image_list.obj.results | json_query(uuid_query) }}"
      vars:
        name_query: "[?controller_info.build.tag.contains(@, '{{ zip_image_version }}')].name"
        type_query: "[?controller_info.build.tag.contains(@, '{{ zip_image_version }}')].type"
        uuid_query: "[?controller_info.build.tag.contains(@, '{{ zip_image_version }}')].uuid"
      tags:
        - prepare

  # Upload the image if it is not yet on the controller
    - name: Calling upload_image role
      include_role:
        name: upload_image
      when: image_name | length == 0
      tags:
        - prepare

    - name: Get our current version
      vmware.alb.avi_api_session:
        avi_credentials: "{{ avi_credentials }}"       
        http_method: get
        timeout: 3000
        path: version/controller
      register: cluster_version
      tags:
        - prepare

    - name: get cluster info
      vmware.alb.avi_api_session:
        avi_credentials: "{{ avi_credentials }}"       
        http_method: get
        timeout: 3000
        path: cluster
      register: cluster_info
      tags:
        - prepare

    - set_fact:
        cluster_uuid: "{{ cluster_info.obj.uuid }}"
      tags:
        - prepare

    - name: end play if already upgraded
      block:
        - debug:
            msg: "This controller is at the same version as the upgrade file"
        - meta: end_play
      when: cluster_version['obj'][0]['version'].split('(')[0] == zip_image_version.split('-')[0] and image_type[0] != "IMAGE_TYPE_PATCH"

  # Configure GSLB maintenance mode. This only runs on the GSLB Leader
    - name: Enable GSLB maintenance mode
      vmware.alb.avi_api_session:
        avi_credentials: "{{ avi_credentials }}"       
        http_method: post
        timeout: 3000
        path: gslbsiteops/maintenancemode
        data:
          enabled: True
      when: gslb.obj.results.0.maintenance_mode == false and cluster_uuid == gslb.obj.results.0.leader_cluster_uuid
