---
- hosts: all
  gather_facts: no
  connection: local
  vars_files: vars.yml
  any_errors_fatal: true
  serial: "{{ serial_count | default(1) }}"
  collections:
    - vmware.alb

  tasks:
    # Calling patch_upgrade role if this is a patch operation
    - name: Calling patch_upgrade role - FOLLOWERS
      import_role:
        name: patch_upgrade
      when: 
        - image_type[0] == "IMAGE_TYPE_PATCH"
        - cluster_uuid != gslb.obj.results.0.leader_cluster_uuid
        - "{{ cluster_version.obj.0.version | compare_versions(zip_image_version) == false }}"
        - "{{ cluster_version.obj.0.patch != patch_image_version }}"

    - name: Calling system_upgrade role - FOLLOWERS
      import_role:
        name: system_upgrade
      when: 
        - image_type[0] == "IMAGE_TYPE_SYSTEM"
        - cluster_uuid != gslb.obj.results.0.leader_cluster_uuid
        - "{{ cluster_version.obj.0.version | compare_versions(zip_image_version) == false }}"

    - name: Monitor Upgrade - FOLLOWERS
      vmware.alb.avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        timeout: 300
        path: "upgradestatusinfo"
      register: upgrade_status
      until: "{{ upgrade_status | upgrade_result() }}"
      delay: 30
      retries: 200
      when: 
        - cluster_uuid != gslb.obj.results.0.leader_cluster_uuid
        - "{{ cluster_version.obj.0.version | compare_versions(zip_image_version) == false }}"
