---
- hosts: all
  connection: local

- name: Prepare Upgrade
  import_playbook: prepare_upgrade.yml

- name: Upgrade GSLB Followers
  import_playbook: upgrade_followers.yml

- name: Upgrade GSLB Leader
  import_playbook: upgrade_leader.yml