---
- name: Upgrade Controller
  vmware.alb.avi_api_session:
    avi_credentials: "{{ avi_credentials }}"
    api_version: "{{ avi_credentials.api_version }}"
    http_method: post
    timeout: 300
    path: "upgrade"
    data:
      image_uuid: "{{ image_uuid.0 }}"
      system: true
      skip_warnings: true
      disruptive: "{{ disruptive_upgrade | default('false') }}"
      suspend_on_failure: "{{ suspend_on_failure | default('true') }}"
      se_group_options:
        action_on_error: "{{ action_on_error | default('SUSPEND_UPGRADE_OPS_ON_ERROR') }}"
